name: GitHub CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.gitattributes'

permissions:
  contents: read

jobs:
  coding-standards:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.3]
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: "Check composer validate"
        run: composer validate --strict --ansi

      - name: "Install dependencies (Composer)"
        uses: ramsey/composer-install@v2
        with:
          composer-options: --prefer-dist --optimize-autoloader --ansi

      - name: "Check composer normalize (composer-normalize)"
        run: composer normalize --dry-run --diff --ansi

      - name: "Check coding standards (PHP-CS-Fixer)"
        run: composer csfixer -- --ansi

  static-analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.1, 8.2, 8.3]
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
      - uses: ramsey/composer-install@v2
        with:
          composer-options: --prefer-dist --optimize-autoloader --ansi

      - name: "Statically analyze code (PHPStan)"
        run: composer phpstan -- --ansi

  rector:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.3]
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
      - uses: ramsey/composer-install@v2
        with:
          composer-options: --prefer-dist --optimize-autoloader --ansi
      - run: composer rector -- --ansi

  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.1, 8.2, 8.3]
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
      - uses: ramsey/composer-install@v2
        with:
          composer-options: --prefer-dist --optimize-autoloader --ansi
      - run: composer test
